Develop
GameCenters/Todo pull request #11
Opened 2022-07-27 12:39 UTC by tuioe5679

### DB 테이블 (todo_list)
- 'id' INT NOT NULL AUTO_INCREMENT PRIMARY KEY ('id'),
-  'title' VARCHAR(45) NOT NULL,
- 'date' VARCHAR(45) NOT NULL,
-  'complete' VARCHAR(5) NOT NULL,

### 요구사항 API
GET:(”/”) 전체 Todo 리스트 조회 

POST: (”/Post”) Todo 리스트 추가

PUT:(”/Update/{id}”) Todo 리스트 수정 

DELETE:(”Delete/{id}”) 특정 Todo 리스트 삭제 

DELETE:(”/AllDelete”) 전체 Todo 리스트 삭제

### 라이브러리 
Spring Web 

MySQL Driver 

Lombok

Spring Data JPA

2022-07-27 12:43 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoList.java
> +}
데이터베이스 테이블 클래스 입니다 
클래스를 통해서 DB에 접근 하게 됩니다 
원래는 클래스 그대로 테이블이 생성된다고 하는데 따로 설정 해야 할것 같습니다 

Spring에서는 JPA가 ORM으로 사용되는것 같네요

2022-07-27 12:44 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/repositroy/TodoListRepository.java
> +public interface TodoListRepository extends JpaRepository<TodoList,Integer> { }
데이터베이스와 만들었던 entity 클래스를 연결시켜주는 인터페이스 입니다 
Service에서 인터페이스를 사용하여 데이터를 처리 합니다

2022-07-27 12:46 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
entity 클래스를 그대로 사용하지 않고 DTO를 따로 만들어서 사용하도록 만들었습니다 
공부했던 CQRS를 여기에 적용 시켜보고 싶네요

2022-07-27 12:56 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +}
Controller에서 요청,응답을 처리하는 Service클래스 입니다 
각 기능마다 메소드를 만들었습니다 

현재는 예외처리가 안되어 있는데 추후 적용 예정입니다

2022-07-27 12:56 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
각 요청에 따라서 Service의 메소드를 호출하여 데이터를 처리또는 응답해주는 클래스입니다 
리턴값으로는 ResponseEntity로 지정하여 HTTP 상태코드와 같이 보내줍니다 

그리고 보내주는 값을 Message 클래스로 감싸서 (상태코드,메시지,Object,개수)로 보내주게 만들었습니다

2022-07-27 12:56 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
Controller에서 사용되는 클래스로 응답 데이터의 상세 정보를 포함하여 보내줄때 사용됩니다

2022-07-27 13:11 UTC, tuioe5679 commented
여러가지를 참고 해서 만들었습니다 
예외 처리,테스트 코드 작성등 해볼 생각이에용 
피드백 주시면 반영 하겠습니다

2022-07-27 14:29 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
이런 성격의 클래스를 뭐라고 부르는지 혹시 아시나용??

아신다면 클래스 명에 적어주면 어떨까용??

```typescript
const message: Message = new Message();
message.message; // String?
message; // Message?
```

코드를 보는 사람 입장에서 엄청 헷갈릴 것 같아서요!

2022-07-27 15:14 UTC, rhea-so requested changes
질문들이 좀 있습니당

2022-07-27 15:14 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
DTO를 한번에 두개 이상을 받는 경우는 인자 명을 어떻게 하실건가용????

2022-07-27 15:14 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
TodoList 생성자에서 인자 순서가 complete, title, date 로 바뀐다면

위에서 DTO로 객체를 만드는 로직들도 바뀌는데

이건 좋은 코드라고 볼 수 있을까용??

만약에 TodoList를 만드는 곳이 100곳이라면, 단순히 인자 순서 바꿨다고 100곳에서 다 에러가 날건데.. 괜찮을까용??

2022-07-27 15:14 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
title만 업데이트 하거나 date만 업데이트 하는 등

TodoList 요소를 부분적으로 업데이트를 하고 싶다는 요구사항이 들어오면 어떻게 수정하실 생각이실지 궁금합니당

2022-07-27 15:14 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
Repository가 id만 가지고 엔티티를 찾아서 지우는 처리를 하고 있네요..

엔티티를 찾고, 지운다는 처리는 서비스 로직 중 하나라고 저는 생각합니당

Repository는 데이터 스토어로써의 역할만 해야지, 찾고 지운다는 서비스 로직의 역할까지 담당하는 건 옳지 못하다고 생각합니당.

원자적으로 바라보는거죵

Repository는 데이터를 저장하고, 삭제하고, 조회하는 기능만 한다.

조회와 삭제를 동시에?? 노우 노우..

아래 코드처럼 구현하는게 더 낫지 않은가란 생각이 들었습니당.

```typescript
const todo: Todo = repository.findOneById(id);
repository.delete(todo);
return true;
```

이러면 나중에 MySQL이 아니라 MongoDB를 쓴다고 했을때 조회와 삭제를 동시에 하는 로직을 안짜줘도 되기도 하고

서비스 클래스만 딱 열어봤을때, 삭제 메서드 속 구현이 조회와 삭제로 구성되어있으니 읽는 사람으로 하여금 좀 더 이해하기 편하게 느껴지지 않을까란 생각입니당.

```typescript
repository.deleteById(id);

// vs

const todo: Todo = repository.findOneById(id);
repository.delete(todo);
```

제 생각이 틀린 것 같다고 생각하시면, 반박 꼭 해주시길 부탁드립니당

2022-07-27 15:14 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +}
TodoListAllDelete 라는 메서드 명이 뭔가 좀 많이 헷갈리네용..

DeleteAllTodo 같은 이름으로 바꿔보면 어떨까용

2022-07-27 15:14 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
근데 이 클래스가 무슨 이유로 필요한건가용??

2022-07-27 15:15 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +@RestController //객체를 반환 데이터를 JSON이나 XML으로 보냄 Controller + ResponseBody
`@RestController`로 해야하는군용... 좋은거 배워갑니당

2022-07-27 15:15 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
이 이외에 다른 메서드 명들도 한번 고민해보심 좋을 것 같아용

2022-07-27 15:16 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoList.java
> +    }
`@NoArgsConstructor//기본 생성자 생성`가 있는데 생성자를 다시 만들어주신 이유가 있으신가용??

2022-07-27 15:17 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    private Message message;
Message는 여기에 왜 있나용??

2022-07-27 15:17 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    private TodoService todoService;
의존성 주입을 이렇게 할 수 있나 보군용 ㄷㄷ

신기하네용

2022-07-27 15:18 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +@AllArgsConstructor// 필드의 모든값을 받는 생성자 생성
이렇게 좋은 기능이 있다니... 부럽네용..

2022-07-27 15:19 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
Class Validator 같은 기능은 없나용??

유저가 title을 넣는 자리에 문자열이 아니라 숫자를 집어넣어서 요청을 보낼수도 있잖아용

2022-07-27 15:21 UTC, rhea-so commented
각각의 요청에 맞는 DTO 클래스가 있었으면 좋을 것 같아용

2022-07-27 15:22 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
각각의 요청에 맞는 DTO 클래스가 있었으면 좋을 것 같아용..

2022-07-28 05:45 UTC, rhea-so commented
> 여러가지를 참고 해서 만들었습니다 예외 처리,테스트 코드 작성등 해볼 생각이에용 피드백 주시면 반영 하겠습니다

어떤걸 참고해서 작업하셨는지 간단하게 링크 정도만 정리해서 올려주시면 되게 좋을 것 같아용

2022-07-28 12:27 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
아뇨 저는 DTO를 통해서 값을 수정하거나 추가할때만 사용하고 있고 
반환은 엔티티 객체를 넘겨주고 있습니다

2022-07-28 12:31 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
CQRS는 명령(변경)역할과 쿼리(조회)의 책임을 분리하는 것이라고 공부했습니다 
현재 프로젝트에는 크게 의미는 없을지는 몰라도 DTO를 따로 만들어서 관리하도록 하고싶습니다

2022-07-28 12:36 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +}
코드를 다른사람이 봤을때 헷갈릴수도 있겠네요 참고하겠습니다 
메소드,변수명 지을때도 고려해서 작성해야겠네요 
다른 메소드명도 바꿔 볼까요?

2022-07-28 12:41 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
음... 잘모르겠습니다 
하지만 객체 이름과 변수 이름이 겹쳐버리네요
이부분은 생각도 못했네요 ㄷㄷ

2022-07-28 12:54 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
data는 TodoList 엔티티 객체를 받고있는데 일단은 Object형으로 지정했습니다 
message는 응답 메시지를 담고있습니다 

data를 TodoList 형으로 바꾸는게 좋을것 같네요

2022-07-28 12:55 UTC, tuioe5679 commented on .idea/uiDesigner.xml
> +</project>
저도 잘 모르겠습니다 
코드 변경하니 갑자기 생성되길래 의문입니다...

2022-07-28 12:59 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    @PostMapping("/Post")
딱히 이유는 없습니다 URL 컨벤션을 몰라서 그냥 작성했네요... 

snake case를 찾아봤는데 단어 표기를 소문자로 하며 띄어쓰기는 _로 표현한다고 이걸 말씀하신건지 궁금합니다 

그리고 snake case를 주로 쓰는군요 알아갑니다

2022-07-28 13:08 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
API 호출시 응답 메시지를 전송하도록 만들었는데요 

말씀 들어보니 꼭 필요한 값은 아니라고 생각이 드네요 

이런 메시지는 오류 발생시 어떤 오류가 일어났는지 보내주는데 쓰이는게 훨씬 좋을것 같습니다

복잡한 행동의 응답은 아직 생각해보지 못했습니다

2022-07-28 13:13 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
저도 두개를 호출하는거는 아니다라고 생각이 들었는데 역시나군요 
size는 프론트 작업할때 혹시나 필요할까봐 넣어봤습니다 
추가,삭제할때 개수를 업데이트 해주는 방식으로 말이죠 

이거는 좋은 방법이 있는지 찾아 봐야겠네요

2022-07-28 13:15 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
넵 한번 고민해보고 바꿔보겠습니다

2022-07-29 00:18 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +}
좋아용

2022-07-29 00:19 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
지금 공부해보신 CQRS를 여기에 적용시켜보면 어떨까용??

다른 프로젝트를 할때 지금의 경험이 굉장히 유용하게 적용될 것 같아 보여서용

2022-07-29 00:21 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
이것도 DTO 입니당

https://velog.io/@ohzzi/Entity-DAO-DTO%EA%B0%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%A9%B0-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C

2022-07-29 00:21 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
이름은 한번 고민해보심 좋을 것 같네용

2022-07-29 00:22 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
근데 그렇게 수정하시면 Message는 TodoList 밖에 못담지않나용??

애초에 이 클래스를 만드신 목적 자체가 모든 응답의 규격화?? 인 것으로 보이는데

그렇게 수정하시면 규격화하는 의미가 없어지지 않나용??

2022-07-29 00:23 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
엔티티 객체와 응답 메시지를 동시에 전달하는 이유가 있을까요??

응답 메시지는 왜 필요한가요??

2022-07-29 00:23 UTC, rhea-so commented on .idea/uiDesigner.xml
> +</project>
오잉.. 일단 넘어가겠습니당..

2022-07-29 00:24 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    @PostMapping("/Post")
녭녭 맞습니당

2022-07-29 00:25 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
개발을 하실때 정말 이게 클라이언트 입장에서 바라봤을때 정말 필요한 데이터인가?

오히려 쓰지도 않는 데이터로 한층 더 감쌌기 때문에 사용하려면 파싱을 한단계 더 해야하므로 더 불편해지는 건 아닌가?

여러방면으로 고민을 해주셨음 좋을 것 같네용

한번 리펙토링 해보실 수 있으실까용??

2022-07-29 00:26 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
저라면 이런 경우에는 

데이터 조회 요청을 받았으니, 데이터를 응답만 하면 되겠네! 라고 생각하고

```typescript
return { todoList: [ new Todo(), new Todo(), new Todo() ] };
```

이런 식으로 구현을 할 것 같아용

2022-07-29 00:27 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
클라이언트 입장에서 더 필요한 데이터가 생겼다? 그러면 그때가서 추가하는거구용

2022-07-29 00:28 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
size가 왜 필요한가용??

프론트에서 배열의 길이를 들고오기만 하면 되는거 아닌가용??

2022-07-29 00:28 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
PR 만드실때 뭔가 아닌 것 같다라고 생각하신게 있으시면

커멘트를 먼저 남겨주세용

저도 보고 같이 고민해볼게용

2022-07-29 00:29 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
녭녭 좋아용

2022-07-29 00:30 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
근데 모든 응답의 형식이 이렇게 똑같을 수 있을까용??

2022-07-29 06:15 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
그러네요 다른 엔티티를 담아서 보낼수 있으니... 수정 조언을 구해봅니다 

프론트에서 해당 작업 내용을 보여주려고 만들었는데 먼가 앞서간 느낌입니다 
응답 메시지는 필요 없을것 같네요 

아니요 달라질수도 있을것 같다고 생각합니다

2022-07-29 06:26 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
인자 명이라면 `TodoListDTO DTO`의 "DTO"를 말씀 하시는건가요
저는 서로 다른 DTO을 받는다면 예를 들어 todoDto로 정할것 같습니다 
이제보니 DTO라는 변수명은 컨벤션에서 조금 어긋나는것 같네요 소문자 작성이 맞는듯 합니다

2022-07-29 06:38 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
와 감사합니다 정말 그러네요 만약 서비스 중이였다면 끔찍하네요 ㄷㄷ 
인자 순서만 바꿨다고 치명적인 오류가 발생하네요 
생성자 보다 set 메소드를 통해서 값을 저장하는 방식으로 바꿔볼께요 

혹시 set 메소드 말고도 좋은 방법이 있다면 알려주십쇼 감사해용

2022-07-29 06:47 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
if문으로 get 메소드를 통해 가져온값이 null 조건을 사용할것같습니다 
이런것 밖에 생각을 못하겠네요 다른 방법이 있다면 알려주시면 감사하겠습니다!

2022-07-29 06:55 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
오 되게 좋은 의견 감사합니다 
단순히 Repository에 찾고 바로 지우는 deleteById()가 있어서 사용했습니다 
역할을 분명히 하고 나누어 사용하는것을 중요시 해야 할것 같아요 

프로그램밍은 정답이 없듯이 여러 의견에 대해 생각하고 반영하는 자세가 좋다고 생각합니다 
물론 정말 잘못된 의견은 좀더 의논을 해야한다고 생각해용 좋은 피드백 감사합니다

2022-07-29 06:59 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
찾아본 자료들 중에서 Message 클래스에 응답에 대한 메시지와 응답 데이터를 담아서 보내주는것이 
프론트와 협업하는데 있어서 좋다는 의견이 있어서 한번 프로젝트에 사용해봤습니다 

그런데 앞서 말씀하신것 처럼 현직 개발자의 의견도 들어보고 싶었습니다 
이것을 사용하는지 협업하는데 정말로 도움이 되는지에 대해서 말이죠

2022-07-29 07:13 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoList.java
> +    }
https://github.com/GameCenters/Todo/pull/11#discussion_r931175996
여기서 사용하도록 따로 추가했습니다 
그런데 피드백 보면 이것도 수정 해야겠네요

2022-07-29 07:14 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    private Message message;
일단 선언 먼저 해놓고 return 에서 객체를 생성후 사용하려고 했습니다

2022-07-29 07:21 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    @PostMapping("/Post")
짜잔

사실 snake case 는 틀렸고

https://velog.io/@juunini/%EB%B2%88%EC%97%AD-22-Best-Practices-to-Take-Your-API-Design-Skills-to-the-Next-Level

케밥 케이스를 씁니다

이걸 읽어보세용

2022-07-29 07:22 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
그렇군요 이것도 한번 알아보고 적용시켜 보겠습니다

2022-07-29 07:24 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
요청,응답 DTO를 따로 만들어 엔티티를 반환하지 않고 DTO를 통해서 반환하는 방식을 말씀하신거죠?

2022-07-29 07:27 UTC, tuioe5679 commented
https://developer-rooney.tistory.com/153?category=496529
https://blog.naver.com/sosow0212/222727249905

https://velog.io/@ansalstmd/Spring-Boot-TodoListApi-Server-%EB%A7%8C%EB%93%A4%EA%B8%B0
이 3개를 중점적으로 공부하고 프로젝트에 적용했습니다 
솔직히 거의 따라한 수준이라고 보시면 될것같네요... ㅎㅎ 
모르는 부분이나 어노테이션등은 따로 알아보면서 사용법,개념들을 주석으로 정리했습니다

2022-07-29 08:36 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    private Message message;
어... 필요가 없네요 착각했네요 
그냥 생성해서 리턴 시켜주는건데 말이죠

2022-07-29 08:58 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
https://github.com/GameCenters/Todo/commit/0d1f8e5e1e88ebaac1a2bb961914d00c7a23f7df
DTO를 따로 만들어서 조회할때는 조회 DTO를 만들어서 반환하도록 하려고 했는데 
`public List<TodoList> TodoList() return todoListRepository.findAll();`

todoListRepository.findAll()메소드의 반환 타입이 TodoList로 되어 있어서 변경을 못했네요
그래서 영역만 나눠서 클래스를 만들었습니다 
 
CQRS의 개념은 이해 했지만 정작 프로젝트에 반영하려니 생각보다 막막하네요

2022-07-29 09:10 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +}
https://github.com/GameCenters/Todo/commit/47f55f0038e156743dec7b211cc505b20a33c47f 이렇게 변경해봤어요 메소드 컨벤션도 고려했습니다

2022-07-29 10:04 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
https://github.com/GameCenters/Todo/commit/63bcd6964a9db65dcff04cd2dae96666e2202197 아예 Message 클래스의 역할을 바꿔버렸습니다 
API 호출시 오류 발생시 ErrorMessage 객체에 메시지와 상태코드를 담아서 보내주도록 하였습니다

2022-07-30 12:13 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
https://github.com/GameCenters/Todo/pull/11#discussion_r933078973
이걸로 바꿨습니당

2022-07-30 12:28 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    @PostMapping("/Post")
https://github.com/GameCenters/Todo/pull/11/commits/6f951c2dc5c11e6afd4bb4526124524dd04c1af8 참고해서 변경 해봤습니다 동사를 안쓴다고 하는데 이게 맞을련지요

2022-07-30 12:32 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
프론트에서 서버로 부터 값을 받고 어떻게 파싱이 이루어지는지 아예 모르다 보니
이런게 조금 있는것 같아요 시간 남으면 프론트도 같이 개발 해봐야 겠네요 
https://github.com/GameCenters/Todo/pull/11/commits/63bcd6964a9db65dcff04cd2dae96666e2202197 변경 사항 입니다 Message 수정커밋 입니다

2022-07-30 12:34 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
https://github.com/GameCenters/Todo/pull/11#discussion_r933078973
나중에 오류 관련 API 만들때 참고 하겠습니다

2022-07-30 12:46 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
https://github.com/GameCenters/Todo/commit/1b60f9d5ae27d1abf65f2bb5ec014e78608d88ce Set 방식으로 초기화 하도록 변경 했습니다 # # #

2022-07-30 12:52 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
https://github.com/GameCenters/Todo/pull/11/commits/7919180f93a49fa7a6bed191856bcc3d1d3f1a22 말씀 하신것 처럼 Repositroy의 역할을 넘어가지 않도록 변경 했습니다

2022-07-30 12:57 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoList.java
> +    }
https://github.com/GameCenters/Todo/pull/11/commits/8f7252f9a9f869a1cabfcdf85009347fada48381 Set 메소드로 초기화 하도록 변경해서 기본 생성자만 사용하도록 했습니다 
https://github.com/GameCenters/Todo/pull/11/commits/62651129c02f9a15392b3745a892cf93dd7ff7a9 명시적 생성자가 사라졌으니 기본생성자 어노테이션도 필요없으니 삭제했습니다

2022-07-30 12:58 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    private Message message;
메시지는 삭제 했습니당

2022-08-01 10:59 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
음.. 굳이 클래스를 분리할 필요가 있을까요..?

개선보다는 관리 포인트만 늘어난 것 같다는 생각이 드네요..

무리해서 분리하다보니 클래스 명에 Command와 Query가 들어가게 되었는데

이거 때문에 네이밍도 엄청 길어지는 것 같구요..

제가 생각한건

### DTO

```java
@Data
public class CreateTodoInput {
    private String title;
    private String date;
}

@Data
public class UpdateTodoInput {
    private Int id;
    private String complete;
}

@Data
public class FindTodoInput {
    private Int id;
}
```

### Controller

```java

@RestController //객체를 반환 데이터를 JSON이나 XML으로 보냄 Controller + ResponseBody
public class QueryTodoController {
    @Autowired
    private QueryTodoService todoService;

    // ▼ Query
    @GetMapping("/todo")
    public ResponseEntity findTodo(@RequestBody input FindTodoInput){
        // do something ...
    }

    // ▼ Command
    @PostMapping("/todo")
    public ResponseEntity createTodo(@RequestBody input CreateTodoInput){
        // do something ...
    }

    // ▼ Command
    @PutMapping("/todo")
    public ResponseEntity updateTodo(@RequestBody input UpdateTodoInput){
        // do something ...
    }
}
```

이런 코드였습니다.

2022-08-01 11:03 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +}
멋져용!

`allGetTodo` 보다는 `todos` 같은건 어떨까용??

2022-08-01 11:05 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
좋아용!

근데 쓰고있는 곳이 없는 것 같은데 그냥 지워버리는게 어떨까용

https://ko.wikipedia.org/wiki/YAGNI

2022-08-01 11:08 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
엔티티를 그대로 응답에 사용하네용.....

만약에 Todo가 아니라 Member일 경우

```typescript
// 엔티티
class Member {
  id: string;
  password: string;
}

// 컨트롤러
return member;
```

를 하면 요청을 보낸 사람은 member.password도 알 수 있겠네용..??

2022-08-01 11:09 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
컨트롤러에서 응답에 필요한 데이터들만 뽑아서 응답 DTO를 만든 뒤,

만든 걸 클라이언트에게 던져야 할 것 같아용

2022-08-01 11:11 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
코타님께서 작성하신 컨트롤러의 존재 의의는

서비스와 클라이언트를 HTTP 통신으로 엮어주는 것에 있습니당

서비스에서 엔티티를 응답했다고 하더라도, HTTP 통신으로 유저의 닉네임 정보만 보낼게~ 라고 규칙을 클라이언트와 서로 정했으면

컨트롤러에서 유저의 닉네임만 뽑아서 응답하도록 해야합니당

-----

자 여기서 왜 서비스에서 유저의 닉네임만 뽑아서 컨트롤러에 반환하게끔 수정하면 되는게 아닌지?

굳이 컨트롤러에서 받은 엔티티의 닉네임 값만 뽑아서 응답해야 하는지??

의문이 생기실 수 있는데 이건 한번 고민해보시겠어용? 왜 그럴까용??

2022-08-01 11:12 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
https://github.com/GameCenters/Todo/pull/11#discussion_r934402099 코드는 이걸 참고하시면 좋을 것 같아용

Input이 있으면 Output이 있게끔..

2022-08-01 11:13 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +}
https://github.com/GameCenters/Todo/commit/6f951c2dc5c11e6afd4bb4526124524dd04c1af8 여기서 todos로 바꾸셨군용 좋습니당

2022-08-01 11:13 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    @PostMapping("/Post")
수고하셨습니다 ~

2022-08-01 11:14 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
프론트 개발을 하지 않고 API를 명확하게 만드는 것이 이번 TODO 프로젝트의 목적이어서

프론트는 안만드시는 걸 추천합니당.

2022-08-01 11:15 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
꼭 프론트를 만들어봐야만 어떻게 파싱이 이뤄지는지,

데이터를 어떻게 쓰는지를 알 수 있는 것 일까요??

요구사항이 명확하지 않아서는 아닐까요?

어떤 요청을 했을때 어떤 응답을 받는다가 요구사항에 있으면 이런 문제는 일어나지 않을 것 같습니당 ㅎㅎ

>개발하다가 생각도 못한 문제로 데이터를 추가를 못한다거나, 추가를 해야한다거나 하는 거라면 모르겠지만..

2022-08-01 11:16 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +                                  todoService.TodoList().size()),HttpStatus.OK);
수고하셨습니다 ~

2022-08-01 11:17 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
수고하셨습니다 ~

2022-08-01 11:18 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
DTO는 축약이어서 다 대문자로 쓰는게 맞다고 저는 생각합니당.

todoDTO로 하신다면 문제는 없겠네용

일단 중요하지 않은거니까 넘어가겠습니당

수고하셨습니다 ~

2022-08-01 11:18 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
수고하셨습니다 ~

2022-08-01 11:20 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
생각하신 방법이 맞습니다 ㅎㅎ

데이터를 받은 경우에만 엔티티의 set을 실행시켜 업데이트를 시켜주는게 좋습니다 ㅎㅎ

2022-08-01 11:20 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/service/TodoService.java
> +    }
수고하셨습니다 ~ 멋져용

2022-08-01 11:22 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
API에서 가장 끔찍한건 object의 깊이가 커지는 것이라고 저는 생각합니당..

깊이가 깊어질수록 하나도 눈에 들어오지 않아서

저는 최대한 평평하게 만드는 것을 좋아합니당

위에서 보내는 데이터들은 클라이언트 입장에서는 필요없는 데이터들인데, 저걸 보내려고 깊이가 1 증가하는거니까... (탭 한번 더 쳐야함)

파싱하는 사람 입장에서는 한번 더 들어가서 파싱을 해야하는거고..

이게 계속 지속되면 형태를 알아볼 수 없는 API가 탄생할 것 같아요..

2022-08-01 11:22 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
협업하는데 좋다는 글 혹시 아시면 공유해주실 수 있나요

전 동의 안해서;;

2022-08-01 11:24 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
네 정확합니당

2022-08-01 11:24 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
좋아요 ~

2022-08-01 11:24 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/controller/TodoController.java
> +    private Message message;
수고하셨습니다 ~

2022-08-01 11:25 UTC, rhea-so commented on todo/src/main/java/com/GameCenter/todo/entity/TodoList.java
> +    }
제가 생각한 것은 이게 아니긴 하지만..

지금 상황에서는 이렇게 구현하는게 더 나을수도 있겠네용..

일단 넘어가겠습니다.

2022-08-01 11:27 UTC, rhea-so reviewed
피드백 답변에 질문을 더 달았습니당

2022-08-01 11:31 UTC, rhea-so commented
PR 명도 Commit 하신 것처럼 변경해주심 좋을 것 같아용 ㅎㅎ

2022-08-02 10:54 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
아직은 무리하게 분리해서 관리할 단계는 아니군요 
각 API에 필요한 인자만 DTO로 받아서 처리하는 코드네요 

불필요한 인자값을 받을 필요가 없는데 제 코드를 보면 모든 값을 다 받게 되어있네요 
제안 하신것 처럼 DTO를 따로 만드는게 좋아보입니다 

여기서는 Input DTO만 만들고 밑에서 Output DTO 만들어서 코멘트 드릴게요

2022-08-02 11:29 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/entity/TodoListDTO.java
> +}
https://github.com/GameCenters/Todo/pull/11/commits/225558f8cb274b27899ded5268ba385396d6628f Controller Service 클래스 그대로 돌려놓고 Create,Update에 사용될 DTO를 만들어주었습니다 

여기서 추가 DTO에 title,date 인자만 받도록 만들었습니다 
그런데 완료값인 complete를 하드코딩으로 Service에서 0으로 초기화 시켜서 DB에 저장하도록 임시로 만들었어요 

default값으로 "0"을 갖도록 만들어서 적용시켜 보려고 합니다 
테이블은 설정을 했는데 엔티티 클래스에서도 같이 설정 해야해서 알아보고 있습니다

2022-08-02 11:32 UTC, tuioe5679 commented on todo/src/main/java/com/GameCenter/todo/controller/Message.java
> +}
https://github.com/GameCenters/Todo/pull/11/commits/2e355f2e8a2705e6bb5e2262c38a062b90a88201 삭제처리 했습니당 나중에 필요하면 그때 만들어야겠네요

2022-08-02 14:00 UTC, rhea-so approved these changes
수고하셨습니다 ~ 👍

2022-08-02 14:04 UTC, merged